#let cfg = (
  lang: "de",
  region: "CH",
  font: ("noto sans", "arial"),
  fontsize: 11pt,
  leading: 0.65em,
  page-numbering: "1/1",
  number-sections: false,
  section-numbering: "1.1.1.1.1",
  authors: ((name: [Author Name], email: "", affiliation: ""),),
  titlepage: false,
  titlepage-rule: 2.5pt + black,
  titlepage-fg: none,
  titlepage-bg: none,
  dateformat: "[day].[month].[year]",
  toc: false,
  toc-depth: 3,
  toc-title: "Inhalt",
  lof-title: "Abbildungsverzeichnis",
  lot-title: "Tabellenverzeichnis",
  smart: true,
  figure-prefix: "Abb.",
  table-prefix: "Tabelle",
  listing-prefix: "Listing",
)
